controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_github_api:
    path: /score/{search_term}
    controller: App\Controller\ScoreController::score
